# Use the official PostgreSQL image as the base
FROM postgres:16-alpine

# Set environment variables for PostgreSQL
ENV POSTGRES_DB=memberbenefitsdb\
    POSTGRES_USER=tester \
    POSTGRES_PASSWORD=tester


# Expose the default PostgreSQL port (optional, but good practice)
EXPOSE 5432