spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/memberbenefitsdb
    username: tester
    password: tester
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
