spring:
  config:
    import: "optional:file:.env[.properties]"
  security:
    user:
      password: test
      name: test
    oauth2:
      client:
        registration:
          google:
            client-id: 45584750029-dpvsmft7l6ju941khpveq4ph0pnfi09h.apps.googleusercontent.com #${GOOGLE_CLIENT_ID}
            client-secret: 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 #${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            issuer-uri: https://accounts.google.com
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/memberbenefitsdb
    username: tester
    password: tester
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

logging:
  file:
    path: C:\Users\02jos\York\Week 3-4\tsg-9-29-member-benefits\backend
    name: backend.log